# -*- coding: utf-8 -*-
"""Topsis_102003220.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zuIe0PdzE4IQ9xK22D_7laxeixb2VLlX
"""

import pandas as pd
import numpy as np

#file upload
mydata=pd.read_csv('/content/Topsis-Dataset.csv')
mydata

#weight
w = [2,3,1,0.5]

#impact
i = [-1, -1, 1, 1]

#element multipy
r = []
for j in range(0, len(w)):
    r.append(w[j] * i[j])

# r

first_column = mydata.columns[0]
# Delete first column
d = mydata.drop([first_column], axis=1)
d.to_csv('file.csv', index=False)
d = pd.DataFrame(d)
d

d1 = d

def func(df, col):
  df[col] = df[col] / np.sqrt(df[col].sum())

d=d*d
# d

# for i in range(len(d)-1):
for i in range(d.shape[1]):
  func(d, d.columns[i])

# d

d=d*r
# d

d.sum(axis=1)

# for i in range(len(d)):
#   d["Topsis Score 2"] = d.sum(axis=1)
# d

d["Topsis Score"] = d.sum(axis=1)
# d

ranks = list(range(len(d)))
Rank = [x for x in ranks]
d['Index']=Rank
# d

d = d.sort_values(by=['Topsis Score'], ascending=False)
# d

ranks = list(range(len(d)))
Rank = [x+1 for x in ranks]
d['Rank']=Rank
# d

d = d.sort_values(by=['Index'])
# d

# d1

d1['Topsis Score'] = d['Topsis Score']
d1['Rank'] = d['Rank']
d1

